### ISSUE TITLE
Design and Implement a Blob Storage Interface (BSI) library and minimal implementation for GCS url signing

### ISSUE THREAD

**Issue by brandonjbjelland** [substratusai/substratus#83]
edit: heavily revised from a CRD to a more lightweight library and gRPC service

## Summary

As discussed this morning, we need a way to create signed URLs in GCS. This concrete task can be generalized considerably and it's likely we'll want to extend this library or service to support more storage operations (e.g. blob storage contents on a path, copy contents of a storage path to a different bucket in a different provider or region, etc.). I don't want to generalize too far beyond storage use cases here (a full Cloud Resource Manager seems overkill). This issue describes the new service implementing a Blob Storage Interface (BSI), its integration points with the core substratus Kubernetes controller.

## Design details

1. Blob Storage Interface (BSI) and GCS implementation:
The BSI will be a protobuf describing request and response payloads and the services it exposes. Our BSI itself is an artifact local to this repo but not something one would deploy - it's just an interface definition. For the first implementation, we'll be supporting Google Cloud Storage (GCS).

2. Kubernetes Controller integration:
Over the longer run, BSI implementations will be separate gRPC services installed optionally by the user potentially from dedicated repos. We'll enable pattern by creating the GCS BSI as a local library, and ideally communicating with it over gRPC.

3. Deployment Options:

We have several options for deploying the BSI within the cluster:

  1. As a separate Deployment with its own Service (available across the clster)
  2. As a sidecar container within the same Pod as the controller.
  3. As a library within the controller code itself.

I'll start as a library under its own directory as `internal/gcsBlobStorageService`. Open to discussion here. Moving toward independent deployments makes more sense in multi-tenant environments.

## Tasks

* [x] Design the BSI with GCS URL signing as the first supported operation. Make sure to design the BSI to be extensible for supporting additional cloud providers and operations in the future.
* [x] implement the gcsBlockStorageService. expose via a service
* [x] * [x] Decide on the deployment strategy for the BSI and implement it.
* [ ] integrate the controller
* [ ] Thoroughly test the core and edge cases.
* [ ] Document the design, usage, and any limitations of the system.

This new system will help us automate and manage our storage resources more securely going forward. Let's discuss this design and identify any potential issues or improvements but I'll likely start in before EOD to get a better handle on the 

As follow up, the kubectl plugin should be extended to be the first client here. Creating a separate issue for that work.

## Open questions

* What/who manages the gcsBlockStorageService Service and Deployment? Is this something the controller launches or the up to the user to install/include? Even implemented as a library, there needs to be an endpoint that exposes the service internally to the cluster (to be port-forwarded).
* It seems simpler to build and run this deployment as an independent gRPC service from the start.
* If the service exposes an endpoint directly, how are callers authorized? I initially assumed the controller was exposing the service via a CRD but in absence of that, we need some sort of external facing endpoint.

## Initial pass suggested protobuf spec:

```proto

```

**Comment by nstogner** [comment]
I think this use case is best solved for using a pattern closer to k8s CSI drivers (

**Comment by nstogner** [comment]
My preference is: short term: in process function call, long term: gRPC call.

**Comment by nstogner** [comment]
IMO, Substratus should avoid CRD pollution, which can cause performance issues with the API server and also increases the cognitive load of administrators (CRDs are user facing - a bunch of them can be overwhelming).

**Comment by brandonjbjelland** [comment]
> IMO, Substratus should avoid CRD pollution, which can cause performance issues with the API server and also increases the cognitive load of administrators (CRDs are user facing - a bunch of them can be overwhelming).

I'm not opposed to taking the approach you're suggesting but do you foresee us approaching CRD pollution? I wouldn't have guessed that. Projects like xp obviously go too far but that's the result of generating (and deploying) hundreds of CRDs. Our domain feels an order of magnitude smaller. I think any managed cluster is capable of scaling to tens of CRDs without issue

**Comment by nstogner** [comment]
I probably should not have mentioned scale as an issue. It is not a major concern of mine and there are some [mitigations](https://blog.upbound.io/scaling-kubernetes-to-thousands-of-crds) coming in later k8s versions.

**Comment by brandonjbjelland** [comment]
All good. Trusting your experience here, just wanting to understand the intuition behind the choices 🙏

**Comment by samos123** [comment]
I think for now all we would need is something like the following implemented in pure golang as a seperate internal PKG:
```
type CloudResourceManager interface {
  GetSignedURL(string url) (string error)
}


func GetSignedURL(string url) (string, error) {
   # GCS golang api call to get signed up load url
   # url would be gs://$BUCKET/$SUBDIR
}
```
Once done Nick can help with implementing it in the controller directly. 

Eventually the pkg call will be replaced by calling a gRPC call to a pod that's running in K8s but that's not needed for initial PR.

There is no need for a separate CRD / controller. For now, any object (Notebook, Image) with an image.upload defined will automatically call GetSignedURL and populate the existing CRD Object (either under image.upload map OR under status fields) with the GCS signed URL.

**Comment by samos123** [comment]
I see the direct work you do in the package to be directly transferrable to the gRPC service.

**Comment by brandonjbjelland** [comment]
> I probably should not have mentioned scale as an issue. It is not a major concern of mine and there are some [mitigations](https://blog.upbound.io/scaling-kubernetes-to-thousands-of-crds) coming in later k8s versions.

I also read this blog post last year! 😄

**Comment by brandonjbjelland** [comment]
Half done here. Calling the service from the controller is next.

**Comment by brandonjbjelland** [comment]
This is complete with some follow up noted in https://github.com/substratusai/substratus/issues/111
