### ISSUE TITLE
Design and Implement a kubectl Plugin for the GCS Blob Storage Interface

### ISSUE THREAD

**Issue by brandonjbjelland** [substratusai/substratus#84]
## Summary
Let's extend the existing kubectl plugin to act as the first client of our GCS Blob Storage Interface (BSI) API. This kubectl plugin will help developers interact with the BSI API more conveniently, direct from the command line.

## Details

As proposed, [BSI](https://github.com/substratusai/substratus/issues/83) is an interface with exactly one implementation on GCS to begin. `GetSignedUrl` is the only service for now.

We could either extend the existing kubectl plugin or create a net-new one that handles BSI-related operations. This plugin will enable users to request signed URLs through a familiar UX.

## Tasks

* [x] Design the user interface for the kubectl plugin. What's the command's name? Flags? Defaults?
* [x] Implement the plugin.
* [x] Package and distribute the plugin as a standalone binary, similar to kubectl-open-notebook. It might make sense to collapse these into a single plugin. Let's discuss.
* [x] test the plugin with various scenarios and edge cases.
* [x] Document the installation process, usage, and limitations.

**Comment by nstogner** [comment]
I would imagine that users would not be interfacing with these APIs, but rather they would actuate them through the existing CRDs... I.e. `kubectl open notebook` would interface with the Notebook API to request and upload URL be provided. It would then send a POST to the upload URL provided by the controller via the Notebook status.

**Comment by brandonjbjelland** [comment]
Resolved by: https://github.com/substratusai/substratus/pull/147
